// Copyright 2017 The LUCI Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// AUTOGENERATED: Do not edit

package rotationproxy

import (
	"github.com/golang/protobuf/proto"

	"go.chromium.org/gae/service/datastore"
)

var _ datastore.PropertyConverter = (*OncallPerson)(nil)

// ToProperty implements datastore.PropertyConverter. It causes an embedded
// 'OncallPerson' to serialize to an unindexed '[]byte' when used with the
// "go.chromium.org/gae" library.
func (p *OncallPerson) ToProperty() (prop datastore.Property, err error) {
	data, err := proto.Marshal(p)
	if err == nil {
		prop.SetValue(data, datastore.NoIndex)
	}
	return
}

// FromProperty implements datastore.PropertyConverter. It parses a '[]byte'
// into an embedded 'OncallPerson' when used with the "go.chromium.org/gae" library.
func (p *OncallPerson) FromProperty(prop datastore.Property) error {
	data, err := prop.Project(datastore.PTBytes)
	if err != nil {
		return err
	}
	return proto.Unmarshal(data.([]byte), p)
}

var _ datastore.PropertyConverter = (*Rotation)(nil)

// ToProperty implements datastore.PropertyConverter. It causes an embedded
// 'Rotation' to serialize to an unindexed '[]byte' when used with the
// "go.chromium.org/gae" library.
func (p *Rotation) ToProperty() (prop datastore.Property, err error) {
	data, err := proto.Marshal(p)
	if err == nil {
		prop.SetValue(data, datastore.NoIndex)
	}
	return
}

// FromProperty implements datastore.PropertyConverter. It parses a '[]byte'
// into an embedded 'Rotation' when used with the "go.chromium.org/gae" library.
func (p *Rotation) FromProperty(prop datastore.Property) error {
	data, err := prop.Project(datastore.PTBytes)
	if err != nil {
		return err
	}
	return proto.Unmarshal(data.([]byte), p)
}

var _ datastore.PropertyConverter = (*Shift)(nil)

// ToProperty implements datastore.PropertyConverter. It causes an embedded
// 'Shift' to serialize to an unindexed '[]byte' when used with the
// "go.chromium.org/gae" library.
func (p *Shift) ToProperty() (prop datastore.Property, err error) {
	data, err := proto.Marshal(p)
	if err == nil {
		prop.SetValue(data, datastore.NoIndex)
	}
	return
}

// FromProperty implements datastore.PropertyConverter. It parses a '[]byte'
// into an embedded 'Shift' when used with the "go.chromium.org/gae" library.
func (p *Shift) FromProperty(prop datastore.Property) error {
	data, err := prop.Project(datastore.PTBytes)
	if err != nil {
		return err
	}
	return proto.Unmarshal(data.([]byte), p)
}
