#!/bin/bash

# Copyright 2019 The LUCI Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This program's only mission in life is to invoke the command 'mockgen'
# and to produce the file swarming.go in the parent directory.
#
# BUG LINK:
# crbug.com/1003844

cd -- "$(dirname -- "${BASH_SOURCE[0]}")" || exit 1
if ! type mockgen 1>/dev/null 2>&1; then
    printf 'error: mockgen not on PATH\n' 1>&2
    exit 1
fi
mockgen -source "$(pwd)/.."/swarming.go -package mock | \
    sed 's|^// Source:.*$|// Source: ../swarming.go via mockgen-wrapper|' > ./swarming.go
