// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/api_proto/feature_objects.proto

package monorail_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Privacy level of a Hotlist.
// Next available tag: 2
type Hotlist_HotlistPrivacy int32

const (
	// Only the owner and editors of the hotlist can view the hotlist.
	Hotlist_PRIVATE Hotlist_HotlistPrivacy = 0
	// Anyone on the web can view the hotlist.
	Hotlist_PUBLIC Hotlist_HotlistPrivacy = 1
)

var Hotlist_HotlistPrivacy_name = map[int32]string{
	0: "PRIVATE",
	1: "PUBLIC",
}

var Hotlist_HotlistPrivacy_value = map[string]int32{
	"PRIVATE": 0,
	"PUBLIC":  1,
}

func (x Hotlist_HotlistPrivacy) String() string {
	return proto.EnumName(Hotlist_HotlistPrivacy_name, int32(x))
}

func (Hotlist_HotlistPrivacy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b79c89226703bd2, []int{0, 0}
}

// A user-owned list of Issues.
// Next available tag: 9
type Hotlist struct {
	// Resource name of the hotlist.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// `display_name` must follow pattern found at `framework_bizobj.RE_HOTLIST_NAME_PATTERN`.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// User who owns the hotlist.
	// Owners can update hotlist settings, editors, owner, and HotlistItems.
	// TODO(monorail:7023): field_behavior may be changed in the future.
	Owner *User `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	// Editors of the hotlist.
	// Editors can update hotlist HotlistItems.
	Editors []*User `protobuf:"bytes,4,rep,name=editors,proto3" json:"editors,omitempty"`
	// Summary of the hotlist.
	Summary string `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	// More detailed description of the purpose of the hotlist.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Ordered list of default columns shown on hotlist's issues list view.
	DefaultColumns       []*IssuesListColumn    `protobuf:"bytes,7,rep,name=default_columns,json=defaultColumns,proto3" json:"default_columns,omitempty"`
	HotlistPrivacy       Hotlist_HotlistPrivacy `protobuf:"varint,8,opt,name=hotlist_privacy,json=hotlistPrivacy,proto3,enum=monorail.v1.Hotlist_HotlistPrivacy" json:"hotlist_privacy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Hotlist) Reset()         { *m = Hotlist{} }
func (m *Hotlist) String() string { return proto.CompactTextString(m) }
func (*Hotlist) ProtoMessage()    {}
func (*Hotlist) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b79c89226703bd2, []int{0}
}

func (m *Hotlist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hotlist.Unmarshal(m, b)
}
func (m *Hotlist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hotlist.Marshal(b, m, deterministic)
}
func (m *Hotlist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hotlist.Merge(m, src)
}
func (m *Hotlist) XXX_Size() int {
	return xxx_messageInfo_Hotlist.Size(m)
}
func (m *Hotlist) XXX_DiscardUnknown() {
	xxx_messageInfo_Hotlist.DiscardUnknown(m)
}

var xxx_messageInfo_Hotlist proto.InternalMessageInfo

func (m *Hotlist) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hotlist) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Hotlist) GetOwner() *User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Hotlist) GetEditors() []*User {
	if m != nil {
		return m.Editors
	}
	return nil
}

func (m *Hotlist) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Hotlist) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Hotlist) GetDefaultColumns() []*IssuesListColumn {
	if m != nil {
		return m.DefaultColumns
	}
	return nil
}

func (m *Hotlist) GetHotlistPrivacy() Hotlist_HotlistPrivacy {
	if m != nil {
		return m.HotlistPrivacy
	}
	return Hotlist_PRIVATE
}

// Represents the the position of an Issue in a Hotlist.
// Next available tag: 7
type HotlistItem struct {
	// Resource name of the HotlistItem.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The Issue associated with this item.
	Issue string `protobuf:"bytes,2,opt,name=issue,proto3" json:"issue,omitempty"`
	// Represents the item's position in the Hotlist in decreasing priority order.
	// Values will be from 1 to N (the size of the hotlist), each item having a unique rank.
	// Changes to rank must be made in `RerankHotlistItems`.
	Rank uint32 `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	// User that added the HotlistItem to the Hotlist.
	Adder *User `protobuf:"bytes,4,opt,name=adder,proto3" json:"adder,omitempty"`
	// The time this HotlistItem was added to the hotlist.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// User-provided additional details about this item.
	Note                 string   `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotlistItem) Reset()         { *m = HotlistItem{} }
func (m *HotlistItem) String() string { return proto.CompactTextString(m) }
func (*HotlistItem) ProtoMessage()    {}
func (*HotlistItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b79c89226703bd2, []int{1}
}

func (m *HotlistItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotlistItem.Unmarshal(m, b)
}
func (m *HotlistItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotlistItem.Marshal(b, m, deterministic)
}
func (m *HotlistItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotlistItem.Merge(m, src)
}
func (m *HotlistItem) XXX_Size() int {
	return xxx_messageInfo_HotlistItem.Size(m)
}
func (m *HotlistItem) XXX_DiscardUnknown() {
	xxx_messageInfo_HotlistItem.DiscardUnknown(m)
}

var xxx_messageInfo_HotlistItem proto.InternalMessageInfo

func (m *HotlistItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HotlistItem) GetIssue() string {
	if m != nil {
		return m.Issue
	}
	return ""
}

func (m *HotlistItem) GetRank() uint32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *HotlistItem) GetAdder() *User {
	if m != nil {
		return m.Adder
	}
	return nil
}

func (m *HotlistItem) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *HotlistItem) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func init() {
	proto.RegisterEnum("monorail.v1.Hotlist_HotlistPrivacy", Hotlist_HotlistPrivacy_name, Hotlist_HotlistPrivacy_value)
	proto.RegisterType((*Hotlist)(nil), "monorail.v1.Hotlist")
	proto.RegisterType((*HotlistItem)(nil), "monorail.v1.HotlistItem")
}

func init() {
	proto.RegisterFile("api/v1/api_proto/feature_objects.proto", fileDescriptor_7b79c89226703bd2)
}

var fileDescriptor_7b79c89226703bd2 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0xdf, 0xc4, 0xf9, 0xf3, 0xb2, 0x86, 0xb4, 0x2c, 0x8a, 0x30, 0x41, 0x15, 0x51, 0x4a,
	0xa3, 0x20, 0x2a, 0x5b, 0x09, 0xb7, 0x9e, 0x70, 0xaa, 0x22, 0x22, 0x45, 0x28, 0xb2, 0x5a, 0xae,
	0xd6, 0xc6, 0x9e, 0x24, 0x0b, 0xb6, 0xd7, 0xda, 0x5d, 0x07, 0x45, 0x15, 0xdf, 0x8b, 0xcf, 0xc2,
	0xa9, 0xe7, 0x7e, 0x04, 0x4e, 0xc8, 0xbb, 0xb6, 0x5a, 0xd3, 0xc0, 0xc9, 0x3b, 0xb3, 0xbf, 0xd9,
	0x19, 0x3f, 0xf3, 0xa0, 0x21, 0x49, 0xa9, 0xb3, 0x1d, 0x3b, 0x24, 0xa5, 0x7e, 0xca, 0x99, 0x64,
	0xce, 0x0a, 0x88, 0xcc, 0x38, 0xf8, 0x6c, 0xf9, 0x05, 0x02, 0x29, 0x6c, 0x95, 0xc5, 0x66, 0xcc,
	0x12, 0xc6, 0x09, 0x8d, 0xec, 0xed, 0xb8, 0x77, 0xba, 0x66, 0x6c, 0x1d, 0x41, 0x51, 0xa0, 0x83,
	0xfc, 0x05, 0x67, 0x45, 0x21, 0x0a, 0xfd, 0x25, 0x6c, 0xc8, 0x96, 0x32, 0xae, 0x4b, 0x7b, 0xc3,
	0xbf, 0xd1, 0x1c, 0x04, 0xcb, 0x78, 0x00, 0x05, 0xf7, 0xaa, 0xb8, 0x52, 0xd1, 0x32, 0x5b, 0x39,
	0x92, 0xc6, 0x20, 0x24, 0x89, 0xd3, 0x02, 0x78, 0xfd, 0x60, 0x56, 0x2a, 0x44, 0xf6, 0xc7, 0xa4,
	0xbd, 0xe3, 0x07, 0x54, 0x26, 0x80, 0x57, 0xa1, 0xc1, 0x4f, 0x03, 0xb5, 0x3f, 0x32, 0x19, 0x51,
	0x21, 0x31, 0x46, 0x8d, 0x84, 0xc4, 0x60, 0xd5, 0xfa, 0xb5, 0xd1, 0x23, 0x4f, 0x9d, 0xf1, 0x10,
	0x3d, 0x0e, 0xa9, 0x48, 0x23, 0xb2, 0xf3, 0xd5, 0x5d, 0x3d, 0xbf, 0x9b, 0x1a, 0x37, 0x6e, 0xdd,
	0x33, 0x8b, 0x8b, 0x4f, 0x39, 0x77, 0x8a, 0x9a, 0xec, 0x5b, 0x02, 0xdc, 0x32, 0xfa, 0xb5, 0x91,
	0x39, 0x79, 0x6a, 0xdf, 0x93, 0xc9, 0xbe, 0x12, 0xc0, 0x75, 0x8d, 0x86, 0xf0, 0x5b, 0xd4, 0x86,
	0x90, 0x4a, 0xc6, 0x85, 0xd5, 0xe8, 0x1b, 0x7b, 0x79, 0xaf, 0x24, 0xf0, 0x11, 0x6a, 0x8b, 0x2c,
	0x8e, 0x09, 0xdf, 0x59, 0xcd, 0xbb, 0xee, 0x65, 0x0e, 0x9f, 0x20, 0x33, 0x04, 0x11, 0x70, 0x9a,
	0x4a, 0xca, 0x12, 0xab, 0x75, 0x7f, 0xc0, 0xbb, 0x3c, 0xfe, 0x80, 0x0e, 0x42, 0x58, 0x91, 0x2c,
	0x92, 0x7e, 0xc0, 0xa2, 0x2c, 0x4e, 0x84, 0xd5, 0x56, 0xad, 0x8f, 0x2a, 0xad, 0x67, 0xb9, 0x90,
	0x62, 0x4e, 0x85, 0x3c, 0x57, 0x94, 0xd7, 0x29, 0xaa, 0x74, 0x28, 0xf0, 0x1c, 0x1d, 0x6c, 0xb4,
	0x5e, 0x7e, 0xca, 0xe9, 0x96, 0x04, 0x3b, 0xeb, 0xff, 0x7e, 0x6d, 0xd4, 0x99, 0x1c, 0x57, 0xde,
	0x29, 0x34, 0x2d, 0xbf, 0x0b, 0x8d, 0x7a, 0x9d, 0x4d, 0x25, 0x1e, 0xbc, 0x41, 0x9d, 0x2a, 0x81,
	0x4d, 0xd4, 0x5e, 0x78, 0xb3, 0xcf, 0xee, 0xe5, 0xc5, 0xe1, 0x7f, 0x18, 0xa1, 0xd6, 0xe2, 0x6a,
	0x3a, 0x9f, 0x9d, 0x1f, 0xd6, 0xce, 0xc6, 0xb7, 0xae, 0x8d, 0xba, 0x24, 0xa5, 0x76, 0xc0, 0x97,
	0xd9, 0xda, 0x0e, 0x58, 0xec, 0x94, 0x9b, 0xeb, 0x16, 0xcf, 0x0a, 0xe7, 0xba, 0x1c, 0x8e, 0x86,
	0xdf, 0x07, 0x3f, 0xea, 0xc8, 0x2c, 0x90, 0x99, 0x84, 0x78, 0xef, 0x82, 0xc7, 0xa8, 0xa9, 0xcc,
	0x53, 0x6c, 0xf6, 0xe5, 0x8d, 0xdb, 0xfc, 0xe5, 0x76, 0xd1, 0xb3, 0x6a, 0x23, 0x25, 0x8b, 0xa7,
	0x49, 0xfc, 0x1c, 0x35, 0x38, 0x49, 0xbe, 0xaa, 0x55, 0x3f, 0xc9, 0xa5, 0x36, 0x3c, 0x95, 0xc8,
	0x4d, 0x40, 0xc2, 0x10, 0xb8, 0xd5, 0xf8, 0x87, 0x09, 0x0c, 0x4f, 0x43, 0xf8, 0x3d, 0x32, 0x03,
	0x0e, 0x44, 0x82, 0x9f, 0xfb, 0x5b, 0xed, 0xd6, 0x9c, 0xf4, 0x6c, 0x6d, 0x7e, 0xbb, 0x34, 0xbf,
	0x7d, 0x59, 0x9a, 0x5f, 0x17, 0x23, 0x5d, 0x93, 0x67, 0xd5, 0xff, 0x30, 0x09, 0x7a, 0xe7, 0x9e,
	0x3a, 0x9f, 0x5d, 0xdc, 0xba, 0x53, 0xf4, 0x62, 0xaf, 0x4c, 0x4a, 0x83, 0x93, 0xbd, 0x52, 0x39,
	0x54, 0x42, 0x2c, 0x9c, 0xeb, 0xfc, 0x93, 0xc7, 0xcb, 0x96, 0xea, 0xff, 0xee, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x89, 0xb9, 0x12, 0xf8, 0x17, 0x04, 0x00, 0x00,
}
