// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/api_proto/projects.proto

package monorail_v1

import prpc "go.chromium.org/luci/grpc/prpc"

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for ListIssueTemplates
// Next available tag: 4
type ListIssueTemplatesRequest struct {
	// The name of the project these templates belong to.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of items to return. The service may return fewer than
	// this value.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListIssueTemplates` call.
	// Provide this to retrieve the subsequent page.
	// When paginating, all other parameters provided to
	// `ListIssueTemplatesRequest` must match the call that provided the token.
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListIssueTemplatesRequest) Reset()         { *m = ListIssueTemplatesRequest{} }
func (m *ListIssueTemplatesRequest) String() string { return proto.CompactTextString(m) }
func (*ListIssueTemplatesRequest) ProtoMessage()    {}
func (*ListIssueTemplatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c420c733c90f8ec5, []int{0}
}

func (m *ListIssueTemplatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIssueTemplatesRequest.Unmarshal(m, b)
}
func (m *ListIssueTemplatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIssueTemplatesRequest.Marshal(b, m, deterministic)
}
func (m *ListIssueTemplatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIssueTemplatesRequest.Merge(m, src)
}
func (m *ListIssueTemplatesRequest) XXX_Size() int {
	return xxx_messageInfo_ListIssueTemplatesRequest.Size(m)
}
func (m *ListIssueTemplatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIssueTemplatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListIssueTemplatesRequest proto.InternalMessageInfo

func (m *ListIssueTemplatesRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListIssueTemplatesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListIssueTemplatesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

// Response message for ListIssueTemplates
// Next available tag: 3
type ListIssueTemplatesResponse struct {
	// Templates matching the given request.
	Templates []*IssueTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListIssueTemplatesResponse) Reset()         { *m = ListIssueTemplatesResponse{} }
func (m *ListIssueTemplatesResponse) String() string { return proto.CompactTextString(m) }
func (*ListIssueTemplatesResponse) ProtoMessage()    {}
func (*ListIssueTemplatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c420c733c90f8ec5, []int{1}
}

func (m *ListIssueTemplatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIssueTemplatesResponse.Unmarshal(m, b)
}
func (m *ListIssueTemplatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIssueTemplatesResponse.Marshal(b, m, deterministic)
}
func (m *ListIssueTemplatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIssueTemplatesResponse.Merge(m, src)
}
func (m *ListIssueTemplatesResponse) XXX_Size() int {
	return xxx_messageInfo_ListIssueTemplatesResponse.Size(m)
}
func (m *ListIssueTemplatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIssueTemplatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListIssueTemplatesResponse proto.InternalMessageInfo

func (m *ListIssueTemplatesResponse) GetTemplates() []*IssueTemplate {
	if m != nil {
		return m.Templates
	}
	return nil
}

func (m *ListIssueTemplatesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// Request message for ListProjects
// Next available tag: 3
type ListProjectsRequest struct {
	// The maximum number of items to return. The service may return fewer than
	// this value.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListProjects` call.
	// Provide this to retrieve the subsequent page.
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsRequest) Reset()         { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()    {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c420c733c90f8ec5, []int{2}
}

func (m *ListProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsRequest.Unmarshal(m, b)
}
func (m *ListProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsRequest.Merge(m, src)
}
func (m *ListProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectsRequest.Size(m)
}
func (m *ListProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsRequest proto.InternalMessageInfo

func (m *ListProjectsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListProjectsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

// Response message for ListProjects
// Next available tag: 3
type ListProjectsResponse struct {
	// Projects matching the given request.
	Projects []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsResponse) Reset()         { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()    {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c420c733c90f8ec5, []int{3}
}

func (m *ListProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsResponse.Unmarshal(m, b)
}
func (m *ListProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsResponse.Marshal(b, m, deterministic)
}
func (m *ListProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResponse.Merge(m, src)
}
func (m *ListProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectsResponse.Size(m)
}
func (m *ListProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResponse proto.InternalMessageInfo

func (m *ListProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *ListProjectsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func init() {
	proto.RegisterType((*ListIssueTemplatesRequest)(nil), "monorail.v1.ListIssueTemplatesRequest")
	proto.RegisterType((*ListIssueTemplatesResponse)(nil), "monorail.v1.ListIssueTemplatesResponse")
	proto.RegisterType((*ListProjectsRequest)(nil), "monorail.v1.ListProjectsRequest")
	proto.RegisterType((*ListProjectsResponse)(nil), "monorail.v1.ListProjectsResponse")
}

func init() {
	proto.RegisterFile("api/v1/api_proto/projects.proto", fileDescriptor_c420c733c90f8ec5)
}

var fileDescriptor_c420c733c90f8ec5 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb1, 0x23, 0xa2, 0x64, 0x02, 0x42, 0x5a, 0x82, 0x30, 0x46, 0x11, 0x26, 0x87, 0x90,
	0x03, 0xb2, 0x49, 0x10, 0x12, 0xd7, 0x70, 0x43, 0xe2, 0x10, 0x4c, 0x38, 0x5b, 0x6b, 0x33, 0x98,
	0x05, 0xc7, 0xbb, 0xec, 0xae, 0xa3, 0x2a, 0x87, 0x3e, 0x42, 0x1f, 0xac, 0x4f, 0xd1, 0xe7, 0xe8,
	0xa9, 0xf2, 0xbf, 0xd4, 0x4e, 0x9a, 0xb4, 0xc7, 0x9d, 0xfd, 0x66, 0xbe, 0xf9, 0x7d, 0x1a, 0x78,
	0x43, 0x05, 0xf3, 0x36, 0x33, 0x8f, 0x0a, 0x16, 0x08, 0xc9, 0x35, 0xf7, 0x84, 0xe4, 0x7f, 0x31,
	0xd2, 0xca, 0x2d, 0x9e, 0x64, 0xb0, 0xe6, 0x29, 0x97, 0x94, 0x25, 0xee, 0x66, 0x66, 0xbf, 0x8f,
	0x39, 0x8f, 0x13, 0xac, 0x94, 0xe5, 0x23, 0x6f, 0xf5, 0x7e, 0x33, 0x4c, 0x7e, 0x05, 0x21, 0xfe,
	0xa1, 0x1b, 0xc6, 0x65, 0xd9, 0x6a, 0x4f, 0x8e, 0xa9, 0x25, 0x2a, 0x9e, 0xc9, 0x08, 0x6b, 0xdd,
	0xb1, 0x1d, 0x02, 0x1e, 0x36, 0x56, 0x19, 0x5f, 0x18, 0xf0, 0xea, 0x1b, 0x53, 0xfa, 0xab, 0x52,
	0x19, 0xae, 0x70, 0x2d, 0x12, 0xaa, 0x51, 0xf9, 0xf8, 0x3f, 0x43, 0xa5, 0xc9, 0x27, 0xe8, 0x0a,
	0x2a, 0x31, 0xd5, 0x96, 0xe1, 0x18, 0xd3, 0xfe, 0x97, 0xd1, 0xd5, 0xc2, 0xbc, 0x5e, 0xbc, 0x84,
	0x17, 0x54, 0x30, 0x37, 0x92, 0x61, 0x16, 0xbb, 0x11, 0x5f, 0x7b, 0xcb, 0x72, 0xb4, 0x5f, 0x89,
	0xc9, 0x6b, 0xe8, 0x0b, 0x1a, 0x63, 0xa0, 0xd8, 0x16, 0x2d, 0xd3, 0x31, 0xa6, 0x8f, 0xfd, 0x5e,
	0x5e, 0xf8, 0xc1, 0xb6, 0x48, 0x46, 0x00, 0xc5, 0xa7, 0xe6, 0xff, 0x30, 0xb5, 0x3a, 0xf9, 0x5c,
	0xbf, 0x90, 0xaf, 0xf2, 0xc2, 0xf8, 0x1c, 0xec, 0xbb, 0xf6, 0x51, 0x82, 0xa7, 0x0a, 0xc9, 0x67,
	0xe8, 0xeb, 0xba, 0x68, 0x19, 0x4e, 0x67, 0x3a, 0x98, 0xdb, 0x6e, 0x23, 0x4d, 0xb7, 0xd5, 0xe7,
	0xdf, 0x8a, 0xc9, 0x04, 0x9e, 0xa5, 0x78, 0xa6, 0x83, 0x86, 0xb7, 0x59, 0x78, 0x3f, 0xcd, 0xcb,
	0xcb, 0x9d, 0xff, 0x77, 0x78, 0x9e, 0xfb, 0x57, 0x48, 0xbb, 0x24, 0x5a, 0x48, 0xc6, 0x49, 0x24,
	0x73, 0x1f, 0x49, 0xc0, 0xb0, 0x3d, 0xb2, 0x82, 0xf9, 0x00, 0xbd, 0xfa, 0x30, 0x2a, 0x96, 0x61,
	0x8b, 0xa5, 0x8e, 0x75, 0xa7, 0x7a, 0x28, 0xc4, 0xfc, 0xd2, 0x80, 0x5e, 0x6d, 0x47, 0x62, 0x20,
	0x87, 0x89, 0x92, 0x49, 0xcb, 0xea, 0xe8, 0x09, 0xd8, 0xef, 0xee, 0xd5, 0x95, 0x34, 0xe3, 0x47,
	0xe4, 0x27, 0x3c, 0x69, 0x72, 0x12, 0xe7, 0xa0, 0x75, 0x2f, 0x55, 0xfb, 0xed, 0x09, 0x45, 0x3d,
	0x36, 0xec, 0x16, 0x97, 0xfa, 0xf1, 0x26, 0x00, 0x00, 0xff, 0xff, 0x61, 0xf0, 0xe1, 0x9a, 0x57,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProjectsClient is the client API for Projects service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectsClient interface {
	// Returns all templates for specified project.
	//
	// Raises:
	//   NOT_FOUND if the requested parent project is not found.
	//   INVALID_ARGUMENT if the given `parent` is not valid.
	ListIssueTemplates(ctx context.Context, in *ListIssueTemplatesRequest, opts ...grpc.CallOption) (*ListIssueTemplatesResponse, error)
	// Returns all projects hosted on Monorail.
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
}
type projectsPRPCClient struct {
	client *prpc.Client
}

func NewProjectsPRPCClient(client *prpc.Client) ProjectsClient {
	return &projectsPRPCClient{client}
}

func (c *projectsPRPCClient) ListIssueTemplates(ctx context.Context, in *ListIssueTemplatesRequest, opts ...grpc.CallOption) (*ListIssueTemplatesResponse, error) {
	out := new(ListIssueTemplatesResponse)
	err := c.client.Call(ctx, "monorail.v1.Projects", "ListIssueTemplates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsPRPCClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	out := new(ListProjectsResponse)
	err := c.client.Call(ctx, "monorail.v1.Projects", "ListProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type projectsClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectsClient(cc grpc.ClientConnInterface) ProjectsClient {
	return &projectsClient{cc}
}

func (c *projectsClient) ListIssueTemplates(ctx context.Context, in *ListIssueTemplatesRequest, opts ...grpc.CallOption) (*ListIssueTemplatesResponse, error) {
	out := new(ListIssueTemplatesResponse)
	err := c.cc.Invoke(ctx, "/monorail.v1.Projects/ListIssueTemplates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, "/monorail.v1.Projects/ListProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectsServer is the server API for Projects service.
type ProjectsServer interface {
	// Returns all templates for specified project.
	//
	// Raises:
	//   NOT_FOUND if the requested parent project is not found.
	//   INVALID_ARGUMENT if the given `parent` is not valid.
	ListIssueTemplates(context.Context, *ListIssueTemplatesRequest) (*ListIssueTemplatesResponse, error)
	// Returns all projects hosted on Monorail.
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
}

// UnimplementedProjectsServer can be embedded to have forward compatible implementations.
type UnimplementedProjectsServer struct {
}

func (*UnimplementedProjectsServer) ListIssueTemplates(ctx context.Context, req *ListIssueTemplatesRequest) (*ListIssueTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIssueTemplates not implemented")
}
func (*UnimplementedProjectsServer) ListProjects(ctx context.Context, req *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}

func RegisterProjectsServer(s prpc.Registrar, srv ProjectsServer) {
	s.RegisterService(&_Projects_serviceDesc, srv)
}

func _Projects_ListIssueTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssueTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).ListIssueTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monorail.v1.Projects/ListIssueTemplates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).ListIssueTemplates(ctx, req.(*ListIssueTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monorail.v1.Projects/ListProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Projects_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monorail.v1.Projects",
	HandlerType: (*ProjectsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIssueTemplates",
			Handler:    _Projects_ListIssueTemplates_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _Projects_ListProjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/api_proto/projects.proto",
}
