// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/api_proto/users.proto

package monorail_v1

import prpc "go.chromium.org/luci/grpc/prpc"

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message for Users.GetUser.
// Next available tag: 2
type GetUserRequest struct {
	// The name of the user to request.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c2dd4221542a287, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The request message for Users.BatchGetUsers.
// Next available tag: 2
type BatchGetUsersRequest struct {
	// The name of the users to request.
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchGetUsersRequest) Reset()         { *m = BatchGetUsersRequest{} }
func (m *BatchGetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*BatchGetUsersRequest) ProtoMessage()    {}
func (*BatchGetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c2dd4221542a287, []int{1}
}

func (m *BatchGetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetUsersRequest.Unmarshal(m, b)
}
func (m *BatchGetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetUsersRequest.Marshal(b, m, deterministic)
}
func (m *BatchGetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetUsersRequest.Merge(m, src)
}
func (m *BatchGetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_BatchGetUsersRequest.Size(m)
}
func (m *BatchGetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetUsersRequest proto.InternalMessageInfo

func (m *BatchGetUsersRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

// The response message for Users.BatchGetUsers.
// Next available tag: 2
type BatchGetUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchGetUsersResponse) Reset()         { *m = BatchGetUsersResponse{} }
func (m *BatchGetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*BatchGetUsersResponse) ProtoMessage()    {}
func (*BatchGetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c2dd4221542a287, []int{2}
}

func (m *BatchGetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetUsersResponse.Unmarshal(m, b)
}
func (m *BatchGetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetUsersResponse.Marshal(b, m, deterministic)
}
func (m *BatchGetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetUsersResponse.Merge(m, src)
}
func (m *BatchGetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_BatchGetUsersResponse.Size(m)
}
func (m *BatchGetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetUsersResponse proto.InternalMessageInfo

func (m *BatchGetUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "monorail.v1.GetUserRequest")
	proto.RegisterType((*BatchGetUsersRequest)(nil), "monorail.v1.BatchGetUsersRequest")
	proto.RegisterType((*BatchGetUsersResponse)(nil), "monorail.v1.BatchGetUsersResponse")
}

func init() { proto.RegisterFile("api/v1/api_proto/users.proto", fileDescriptor_2c2dd4221542a287) }

var fileDescriptor_2c2dd4221542a287 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x9b, 0xff, 0xb7, 0x8a, 0xb7, 0x28, 0x38, 0x54, 0x90, 0xe8, 0x42, 0x23, 0xa8, 0x0b,
	0x99, 0xd0, 0xba, 0x74, 0xd3, 0x76, 0xa1, 0x7b, 0x41, 0x70, 0x17, 0x26, 0xe3, 0x35, 0x1d, 0x49,
	0x72, 0xc7, 0x99, 0x49, 0x1e, 0xc7, 0x67, 0xf3, 0x39, 0x5c, 0x89, 0x93, 0x59, 0x18, 0x5b, 0xc5,
	0x5d, 0xc2, 0x7c, 0xe7, 0xe3, 0x9e, 0x03, 0x47, 0x42, 0xab, 0xb4, 0x9d, 0xa4, 0x42, 0xab, 0x4c,
	0x1b, 0x72, 0x94, 0x36, 0x16, 0x8d, 0xe5, 0xfe, 0x9b, 0x8d, 0x2a, 0xaa, 0xc9, 0x08, 0x55, 0xf2,
	0x76, 0x12, 0x5f, 0x16, 0x44, 0x45, 0x89, 0x01, 0xeb, 0x7e, 0x3e, 0x73, 0xe9, 0x93, 0xc2, 0xf2,
	0x31, 0xcb, 0x71, 0x29, 0x5a, 0x45, 0xa6, 0x8b, 0xc6, 0x67, 0x3f, 0xd1, 0x06, 0x2d, 0x35, 0x46,
	0x62, 0xe0, 0x4e, 0xd7, 0x1e, 0x90, 0x51, 0xfe, 0x8c, 0xd2, 0x85, 0x3b, 0x92, 0x19, 0xec, 0xde,
	0xa2, 0xbb, 0xb7, 0x68, 0xee, 0xf0, 0xa5, 0x41, 0xeb, 0x18, 0x87, 0x8d, 0x5a, 0x54, 0x78, 0x10,
	0x1d, 0x47, 0x17, 0xdb, 0x8b, 0xf8, 0x6d, 0xfe, 0xef, 0x7d, 0x3e, 0x06, 0x26, 0xb4, 0xe2, 0xd2,
	0xe4, 0x4d, 0xc1, 0x25, 0x55, 0xa9, 0x0f, 0x78, 0x2e, 0xb9, 0x81, 0xf1, 0x42, 0x38, 0xb9, 0x0c,
	0x1a, 0xbb, 0xea, 0xf9, 0xff, 0x27, 0xcf, 0x0c, 0xf6, 0xbf, 0x79, 0xac, 0xa6, 0xda, 0x22, 0x3b,
	0x87, 0xa1, 0x5f, 0xce, 0x9b, 0x46, 0xd3, 0x3d, 0xfe, 0x65, 0x3a, 0xee, 0x05, 0xdd, 0xfb, 0xf4,
	0x35, 0x82, 0xa1, 0x8f, 0xb2, 0x6b, 0xd8, 0x0a, 0x1a, 0x76, 0xd8, 0xc3, 0xfb, 0x5d, 0xe3, 0x55,
	0x57, 0x32, 0x60, 0x0f, 0xb0, 0xd3, 0x3b, 0x84, 0x9d, 0xf4, 0xa8, 0x75, 0x65, 0xe3, 0xe4, 0x37,
	0xa4, 0xeb, 0x91, 0x0c, 0xf2, 0x4d, 0xbf, 0xf9, 0xd5, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13,
	0x85, 0xc7, 0x16, 0x1b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	// Returns the requested User.
	// TODO(crbug/monorail/7238): Document possible errors when implemented.
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	// Returns all of the requested Users.
	// TODO(crbug/monorail/7238): Document possible errors when implemented.
	BatchGetUsers(ctx context.Context, in *BatchGetUsersRequest, opts ...grpc.CallOption) (*BatchGetUsersResponse, error)
}
type usersPRPCClient struct {
	client *prpc.Client
}

func NewUsersPRPCClient(client *prpc.Client) UsersClient {
	return &usersPRPCClient{client}
}

func (c *usersPRPCClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.client.Call(ctx, "monorail.v1.Users", "GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersPRPCClient) BatchGetUsers(ctx context.Context, in *BatchGetUsersRequest, opts ...grpc.CallOption) (*BatchGetUsersResponse, error) {
	out := new(BatchGetUsersResponse)
	err := c.client.Call(ctx, "monorail.v1.Users", "BatchGetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type usersClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersClient(cc grpc.ClientConnInterface) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/monorail.v1.Users/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) BatchGetUsers(ctx context.Context, in *BatchGetUsersRequest, opts ...grpc.CallOption) (*BatchGetUsersResponse, error) {
	out := new(BatchGetUsersResponse)
	err := c.cc.Invoke(ctx, "/monorail.v1.Users/BatchGetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	// Returns the requested User.
	// TODO(crbug/monorail/7238): Document possible errors when implemented.
	GetUser(context.Context, *GetUserRequest) (*User, error)
	// Returns all of the requested Users.
	// TODO(crbug/monorail/7238): Document possible errors when implemented.
	BatchGetUsers(context.Context, *BatchGetUsersRequest) (*BatchGetUsersResponse, error)
}

// UnimplementedUsersServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (*UnimplementedUsersServer) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUsersServer) BatchGetUsers(ctx context.Context, req *BatchGetUsersRequest) (*BatchGetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetUsers not implemented")
}

func RegisterUsersServer(s prpc.Registrar, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monorail.v1.Users/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_BatchGetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).BatchGetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monorail.v1.Users/BatchGetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).BatchGetUsers(ctx, req.(*BatchGetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monorail.v1.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Users_GetUser_Handler,
		},
		{
			MethodName: "BatchGetUsers",
			Handler:    _Users_BatchGetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/api_proto/users.proto",
}
