runtime: go113
service: default

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
# Reference: https://chromium.googlesource.com/infra/luci/luci-go/+/refs/heads/master/examples/appengine/helloworld_v2/app.yaml
luci_gae_vars:
  unified-fleet-system-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
  unified-fleet-system-prod:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com

entrypoint: >
  /usr/local/bin/start -auth-service-host ${AUTH_SERVICE_HOST}
