// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/appengine/unified-fleet/app/config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Config is the configuration data served by luci-config for this app.
type Config struct {
	LuciConfigService    string   `protobuf:"bytes,1,opt,name=luci_config_service,json=luciConfigService,proto3" json:"luci_config_service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_04cb6a48b01a1d3b, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLuciConfigService() string {
	if m != nil {
		return m.LuciConfigService
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "ufs.config.Config")
}

func init() {
	proto.RegisterFile("infra/appengine/unified-fleet/app/config/config.proto", fileDescriptor_04cb6a48b01a1d3b)
}

var fileDescriptor_04cb6a48b01a1d3b = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xcd, 0xcc, 0x4b, 0x2b,
	0x4a, 0xd4, 0x4f, 0x2c, 0x28, 0x48, 0xcd, 0x4b, 0xcf, 0xcc, 0x4b, 0xd5, 0x2f, 0xcd, 0xcb, 0x4c,
	0xcb, 0x4c, 0x4d, 0xd1, 0x4d, 0xcb, 0x49, 0x4d, 0x2d, 0x01, 0x89, 0xeb, 0x27, 0xe7, 0xe7, 0xa5,
	0x65, 0xa6, 0x43, 0x29, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0xae, 0xd2, 0xb4, 0x62, 0x3d,
	0x88, 0x88, 0x92, 0x05, 0x17, 0x9b, 0x33, 0x98, 0x25, 0xa4, 0xc7, 0x25, 0x9c, 0x53, 0x9a, 0x9c,
	0x19, 0x0f, 0x91, 0x88, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x12, 0x04, 0x49, 0x41, 0x14, 0x06, 0x43, 0x24, 0x9c, 0x38, 0xa2, 0xd8, 0x20, 0x4a,
	0x93, 0xd8, 0xc0, 0xc6, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x08, 0xf9, 0xff, 0x8f,
	0x00, 0x00, 0x00,
}
