// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/appengine/cros/lab_inventory/app/config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LuciAuthGroup struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LuciAuthGroup) Reset()         { *m = LuciAuthGroup{} }
func (m *LuciAuthGroup) String() string { return proto.CompactTextString(m) }
func (*LuciAuthGroup) ProtoMessage()    {}
func (*LuciAuthGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe4d2048e3798022, []int{0}
}

func (m *LuciAuthGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LuciAuthGroup.Unmarshal(m, b)
}
func (m *LuciAuthGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LuciAuthGroup.Marshal(b, m, deterministic)
}
func (m *LuciAuthGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LuciAuthGroup.Merge(m, src)
}
func (m *LuciAuthGroup) XXX_Size() int {
	return xxx_messageInfo_LuciAuthGroup.Size(m)
}
func (m *LuciAuthGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_LuciAuthGroup.DiscardUnknown(m)
}

var xxx_messageInfo_LuciAuthGroup proto.InternalMessageInfo

func (m *LuciAuthGroup) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Config is the configuration data served by luci-config for this app.
type Config struct {
	// AdminService contains information about the skylab admin instances.
	AdminService *AdminService `protobuf:"bytes,2,opt,name=admin_service,json=adminService,proto3" json:"admin_service,omitempty"`
	// The access groups of the inventory.
	Readers                   *LuciAuthGroup `protobuf:"bytes,3,opt,name=readers,proto3" json:"readers,omitempty"`
	StatusWriters             *LuciAuthGroup `protobuf:"bytes,4,opt,name=status_writers,json=statusWriters,proto3" json:"status_writers,omitempty"`
	SetupWriters              *LuciAuthGroup `protobuf:"bytes,5,opt,name=setup_writers,json=setupWriters,proto3" json:"setup_writers,omitempty"`
	PrivilegedWriters         *LuciAuthGroup `protobuf:"bytes,6,opt,name=privileged_writers,json=privilegedWriters,proto3" json:"privileged_writers,omitempty"`
	HwidSecret                string         `protobuf:"bytes,7,opt,name=hwid_secret,json=hwidSecret,proto3" json:"hwid_secret,omitempty"`
	DeviceConfigSource        *Gitiles       `protobuf:"bytes,8,opt,name=device_config_source,json=deviceConfigSource,proto3" json:"device_config_source,omitempty"`
	ManufacturingConfigSource *Gitiles       `protobuf:"bytes,9,opt,name=manufacturing_config_source,json=manufacturingConfigSource,proto3" json:"manufacturing_config_source,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}       `json:"-"`
	XXX_unrecognized          []byte         `json:"-"`
	XXX_sizecache             int32          `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe4d2048e3798022, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetAdminService() *AdminService {
	if m != nil {
		return m.AdminService
	}
	return nil
}

func (m *Config) GetReaders() *LuciAuthGroup {
	if m != nil {
		return m.Readers
	}
	return nil
}

func (m *Config) GetStatusWriters() *LuciAuthGroup {
	if m != nil {
		return m.StatusWriters
	}
	return nil
}

func (m *Config) GetSetupWriters() *LuciAuthGroup {
	if m != nil {
		return m.SetupWriters
	}
	return nil
}

func (m *Config) GetPrivilegedWriters() *LuciAuthGroup {
	if m != nil {
		return m.PrivilegedWriters
	}
	return nil
}

func (m *Config) GetHwidSecret() string {
	if m != nil {
		return m.HwidSecret
	}
	return ""
}

func (m *Config) GetDeviceConfigSource() *Gitiles {
	if m != nil {
		return m.DeviceConfigSource
	}
	return nil
}

func (m *Config) GetManufacturingConfigSource() *Gitiles {
	if m != nil {
		return m.ManufacturingConfigSource
	}
	return nil
}

type AdminService struct {
	// The skylab admin GAE server hosting the admin services.
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminService) Reset()         { *m = AdminService{} }
func (m *AdminService) String() string { return proto.CompactTextString(m) }
func (*AdminService) ProtoMessage()    {}
func (*AdminService) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe4d2048e3798022, []int{2}
}

func (m *AdminService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminService.Unmarshal(m, b)
}
func (m *AdminService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminService.Marshal(b, m, deterministic)
}
func (m *AdminService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminService.Merge(m, src)
}
func (m *AdminService) XXX_Size() int {
	return xxx_messageInfo_AdminService.Size(m)
}
func (m *AdminService) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminService.DiscardUnknown(m)
}

var xxx_messageInfo_AdminService proto.InternalMessageInfo

func (m *AdminService) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type Gitiles struct {
	// The gitiles host name, e.g. 'chrome-internal.googlesource.com'.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// The project (repo) name, e.g. 'chromeos/infra/config'.
	Project string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	// The commit hash/branch to be checked out, e.g. 'refs/heads/master'.
	Committish string `protobuf:"bytes,3,opt,name=committish,proto3" json:"committish,omitempty"`
	// The path of the file to be downloaded, e.g. 'path/to/file.cfg'.
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gitiles) Reset()         { *m = Gitiles{} }
func (m *Gitiles) String() string { return proto.CompactTextString(m) }
func (*Gitiles) ProtoMessage()    {}
func (*Gitiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe4d2048e3798022, []int{3}
}

func (m *Gitiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gitiles.Unmarshal(m, b)
}
func (m *Gitiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gitiles.Marshal(b, m, deterministic)
}
func (m *Gitiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gitiles.Merge(m, src)
}
func (m *Gitiles) XXX_Size() int {
	return xxx_messageInfo_Gitiles.Size(m)
}
func (m *Gitiles) XXX_DiscardUnknown() {
	xxx_messageInfo_Gitiles.DiscardUnknown(m)
}

var xxx_messageInfo_Gitiles proto.InternalMessageInfo

func (m *Gitiles) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Gitiles) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Gitiles) GetCommittish() string {
	if m != nil {
		return m.Committish
	}
	return ""
}

func (m *Gitiles) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*LuciAuthGroup)(nil), "lab_inventory.config.LuciAuthGroup")
	proto.RegisterType((*Config)(nil), "lab_inventory.config.Config")
	proto.RegisterType((*AdminService)(nil), "lab_inventory.config.AdminService")
	proto.RegisterType((*Gitiles)(nil), "lab_inventory.config.Gitiles")
}

func init() {
	proto.RegisterFile("infra/appengine/cros/lab_inventory/app/config/config.proto", fileDescriptor_fe4d2048e3798022)
}

var fileDescriptor_fe4d2048e3798022 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0xe9, 0xda, 0x6d, 0x9b, 0xb7, 0xad, 0xe8, 0xd0, 0x43, 0x44, 0xd4, 0x25, 0x22, 0xec,
	0xa9, 0x05, 0xbd, 0x09, 0x1e, 0x56, 0x0f, 0x95, 0x45, 0x10, 0xa6, 0x07, 0x41, 0x90, 0x30, 0x3b,
	0x79, 0x6d, 0x9e, 0xb6, 0x33, 0xc3, 0xfc, 0xe8, 0xe2, 0x9f, 0xe9, 0x7f, 0x24, 0x99, 0x69, 0x6b,
	0x2b, 0x39, 0xe4, 0x94, 0x79, 0x3f, 0xbe, 0x9f, 0x97, 0xe4, 0x7d, 0x07, 0xde, 0x93, 0x5a, 0x59,
	0x31, 0x17, 0xc6, 0xa0, 0x5a, 0x93, 0xc2, 0xb9, 0xb4, 0xda, 0xcd, 0x37, 0xe2, 0xbe, 0x24, 0xb5,
	0x43, 0xe5, 0xb5, 0xfd, 0xdd, 0x14, 0xe7, 0x52, 0xab, 0x15, 0xad, 0xf7, 0x8f, 0x99, 0xb1, 0xda,
	0x6b, 0x36, 0x3d, 0x6b, 0x9b, 0xa5, 0x5a, 0xf1, 0x06, 0x26, 0x5f, 0x82, 0xa4, 0xdb, 0xe0, 0xeb,
	0x85, 0xd5, 0xc1, 0xb0, 0x29, 0x5c, 0xee, 0xc4, 0x26, 0x60, 0xde, 0xbb, 0xee, 0xdd, 0x64, 0x3c,
	0x05, 0xc5, 0x9f, 0x3e, 0x0c, 0x3e, 0x45, 0x05, 0x5b, 0xc0, 0x44, 0x54, 0x5b, 0x52, 0xa5, 0x43,
	0xbb, 0x23, 0x89, 0xf9, 0xc5, 0x75, 0xef, 0xe6, 0xea, 0x6d, 0x31, 0x6b, 0xe3, 0xcf, 0x6e, 0x9b,
	0xd6, 0x65, 0xea, 0xe4, 0x63, 0x71, 0x12, 0xb1, 0x0f, 0x30, 0xb4, 0x28, 0x2a, 0xb4, 0x2e, 0x7f,
	0x14, 0x11, 0xaf, 0xdb, 0x11, 0x67, 0xef, 0xc7, 0x0f, 0x1a, 0x76, 0x07, 0x8f, 0x9d, 0x17, 0x3e,
	0xb8, 0xf2, 0xc1, 0x92, 0x6f, 0x28, 0xfd, 0xee, 0x94, 0x49, 0x92, 0x7e, 0x4b, 0x4a, 0xf6, 0x19,
	0x26, 0x0e, 0x7d, 0x30, 0x47, 0xd4, 0x65, 0x77, 0xd4, 0x38, 0x2a, 0x0f, 0x24, 0x0e, 0xcc, 0x58,
	0xda, 0xd1, 0x06, 0xd7, 0x58, 0x1d, 0x71, 0x83, 0xee, 0xb8, 0xa7, 0xff, 0xe4, 0x07, 0xe6, 0x2b,
	0xb8, 0xaa, 0x1f, 0xa8, 0x2a, 0x1d, 0x4a, 0x8b, 0x3e, 0x1f, 0xc6, 0xc5, 0x40, 0x93, 0x5a, 0xc6,
	0x0c, 0xfb, 0x0a, 0xd3, 0x0a, 0x9b, 0x7f, 0x5a, 0x26, 0x64, 0xe9, 0x74, 0xb0, 0x12, 0xf3, 0x51,
	0x1c, 0xfb, 0xa2, 0x7d, 0xec, 0x82, 0x3c, 0x6d, 0xd0, 0x71, 0x96, 0xa4, 0x69, 0xbb, 0xcb, 0x28,
	0x64, 0x3f, 0xe0, 0xf9, 0x56, 0xa8, 0xb0, 0x12, 0xd2, 0x07, 0x4b, 0x6a, 0xfd, 0x1f, 0x37, 0xeb,
	0xc2, 0x7d, 0x76, 0x46, 0x38, 0xc5, 0xdf, 0xf5, 0x47, 0xbd, 0x27, 0x17, 0x45, 0x01, 0xe3, 0x53,
	0x77, 0x30, 0x06, 0xfd, 0x5a, 0x3b, 0xbf, 0x37, 0x5e, 0x3c, 0x17, 0xbf, 0x60, 0xb8, 0xe7, 0xb5,
	0x95, 0x59, 0x0e, 0x43, 0x63, 0xf5, 0x4f, 0x94, 0x3e, 0xba, 0x30, 0xe3, 0x87, 0x90, 0xbd, 0x04,
	0x90, 0x7a, 0xbb, 0x25, 0xef, 0xc9, 0xd5, 0xd1, 0x5f, 0x19, 0x3f, 0xc9, 0x34, 0x34, 0x23, 0x7c,
	0x1d, 0x3d, 0x93, 0xf1, 0x78, 0xfe, 0x38, 0xfa, 0x3e, 0x48, 0xdf, 0x70, 0x3f, 0x88, 0x57, 0xe6,
	0xdd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xee, 0xa7, 0x1e, 0x70, 0x03, 0x00, 0x00,
}
