// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/appengine/unified-fleet/api/v1/proto/machine.proto

package ufspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ChromeOSDeviceType refers to the different types of
// device/machine in the Chrome OS lab
type ChromeOSDeviceType int32

const (
	ChromeOSDeviceType_CHROME_OS_DEVICE_TYPE_UNSPECIFIED ChromeOSDeviceType = 0
	ChromeOSDeviceType_DEVICE_CHROMEBOOK                 ChromeOSDeviceType = 1
	ChromeOSDeviceType_DEVICE_LABSTATION                 ChromeOSDeviceType = 2
	ChromeOSDeviceType_DEVICE_SERVO                      ChromeOSDeviceType = 3
)

var ChromeOSDeviceType_name = map[int32]string{
	0: "CHROME_OS_DEVICE_TYPE_UNSPECIFIED",
	1: "DEVICE_CHROMEBOOK",
	2: "DEVICE_LABSTATION",
	3: "DEVICE_SERVO",
}

var ChromeOSDeviceType_value = map[string]int32{
	"CHROME_OS_DEVICE_TYPE_UNSPECIFIED": 0,
	"DEVICE_CHROMEBOOK":                 1,
	"DEVICE_LABSTATION":                 2,
	"DEVICE_SERVO":                      3,
}

func (x ChromeOSDeviceType) String() string {
	return proto.EnumName(ChromeOSDeviceType_name, int32(x))
}

func (ChromeOSDeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bcb58b98328ec12c, []int{0}
}

// Machine refers to the devices or bare metal servers
// which serves the tests directly.
type Machine struct {
	// A unique name for the machine.
	//   * AssetTag for ChromeOS machine (device)
	//   * Serial number for Chrome machine for now (server) (Ideally it should be assetTag once it’s ready)
	// The format will be machines/asset:XXX or machines/sn:XXX
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// serial_number of the machine.
	SerialNumber string `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	// Location details of where the machine is placed
	Location *Location `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// Types that are valid to be assigned to Device:
	//	*Machine_ChromeBrowserMachine
	//	*Machine_ChromeosMachine
	Device isMachine_Device `protobuf_oneof:"device"`
	// Record the last update timestamp of this machine (In UTC timezone)
	UpdateTime *timestamp.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Record the ACL info of the machine
	Realm                string   `protobuf:"bytes,7,opt,name=realm,proto3" json:"realm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Machine) Reset()         { *m = Machine{} }
func (m *Machine) String() string { return proto.CompactTextString(m) }
func (*Machine) ProtoMessage()    {}
func (*Machine) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcb58b98328ec12c, []int{0}
}

func (m *Machine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Machine.Unmarshal(m, b)
}
func (m *Machine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Machine.Marshal(b, m, deterministic)
}
func (m *Machine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Machine.Merge(m, src)
}
func (m *Machine) XXX_Size() int {
	return xxx_messageInfo_Machine.Size(m)
}
func (m *Machine) XXX_DiscardUnknown() {
	xxx_messageInfo_Machine.DiscardUnknown(m)
}

var xxx_messageInfo_Machine proto.InternalMessageInfo

func (m *Machine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Machine) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Machine) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type isMachine_Device interface {
	isMachine_Device()
}

type Machine_ChromeBrowserMachine struct {
	ChromeBrowserMachine *ChromeBrowserMachine `protobuf:"bytes,4,opt,name=chrome_browser_machine,json=chromeBrowserMachine,proto3,oneof"`
}

type Machine_ChromeosMachine struct {
	ChromeosMachine *ChromeOSMachine `protobuf:"bytes,5,opt,name=chromeos_machine,json=chromeosMachine,proto3,oneof"`
}

func (*Machine_ChromeBrowserMachine) isMachine_Device() {}

func (*Machine_ChromeosMachine) isMachine_Device() {}

func (m *Machine) GetDevice() isMachine_Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *Machine) GetChromeBrowserMachine() *ChromeBrowserMachine {
	if x, ok := m.GetDevice().(*Machine_ChromeBrowserMachine); ok {
		return x.ChromeBrowserMachine
	}
	return nil
}

func (m *Machine) GetChromeosMachine() *ChromeOSMachine {
	if x, ok := m.GetDevice().(*Machine_ChromeosMachine); ok {
		return x.ChromeosMachine
	}
	return nil
}

func (m *Machine) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Machine) GetRealm() string {
	if m != nil {
		return m.Realm
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Machine) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Machine_ChromeBrowserMachine)(nil),
		(*Machine_ChromeosMachine)(nil),
	}
}

// ChromeBrowserMachine refers to bare metal servers in Chrome Browser lab
type ChromeBrowserMachine struct {
	// Descriptive name of Chrome Machine
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Should match one of the predefined Chrome Platforms.
	Platform *ChromePlatform `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// Refers to Nic name
	Nic *Nic `protobuf:"bytes,3,opt,name=nic,proto3" json:"nic,omitempty"`
	// Interface of its connected devices.
	KvmInterface           *KVMInterface    `protobuf:"bytes,4,opt,name=kvm_interface,json=kvmInterface,proto3" json:"kvm_interface,omitempty"`
	RpmInterface           *RPMInterface    `protobuf:"bytes,5,opt,name=rpm_interface,json=rpmInterface,proto3" json:"rpm_interface,omitempty"`
	NetworkDeviceInterface *SwitchInterface `protobuf:"bytes,6,opt,name=network_device_interface,json=networkDeviceInterface,proto3" json:"network_device_interface,omitempty"`
	Drac                   *Drac            `protobuf:"bytes,7,opt,name=drac,proto3" json:"drac,omitempty"`
	// Usually it's a buganizer bug.
	DeploymentTicket string `protobuf:"bytes,8,opt,name=deployment_ticket,json=deploymentTicket,proto3" json:"deployment_ticket,omitempty"`
	// Can be covered by deployment_ticket
	Description          string   `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChromeBrowserMachine) Reset()         { *m = ChromeBrowserMachine{} }
func (m *ChromeBrowserMachine) String() string { return proto.CompactTextString(m) }
func (*ChromeBrowserMachine) ProtoMessage()    {}
func (*ChromeBrowserMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcb58b98328ec12c, []int{1}
}

func (m *ChromeBrowserMachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChromeBrowserMachine.Unmarshal(m, b)
}
func (m *ChromeBrowserMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChromeBrowserMachine.Marshal(b, m, deterministic)
}
func (m *ChromeBrowserMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChromeBrowserMachine.Merge(m, src)
}
func (m *ChromeBrowserMachine) XXX_Size() int {
	return xxx_messageInfo_ChromeBrowserMachine.Size(m)
}
func (m *ChromeBrowserMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_ChromeBrowserMachine.DiscardUnknown(m)
}

var xxx_messageInfo_ChromeBrowserMachine proto.InternalMessageInfo

func (m *ChromeBrowserMachine) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ChromeBrowserMachine) GetPlatform() *ChromePlatform {
	if m != nil {
		return m.Platform
	}
	return nil
}

func (m *ChromeBrowserMachine) GetNic() *Nic {
	if m != nil {
		return m.Nic
	}
	return nil
}

func (m *ChromeBrowserMachine) GetKvmInterface() *KVMInterface {
	if m != nil {
		return m.KvmInterface
	}
	return nil
}

func (m *ChromeBrowserMachine) GetRpmInterface() *RPMInterface {
	if m != nil {
		return m.RpmInterface
	}
	return nil
}

func (m *ChromeBrowserMachine) GetNetworkDeviceInterface() *SwitchInterface {
	if m != nil {
		return m.NetworkDeviceInterface
	}
	return nil
}

func (m *ChromeBrowserMachine) GetDrac() *Drac {
	if m != nil {
		return m.Drac
	}
	return nil
}

func (m *ChromeBrowserMachine) GetDeploymentTicket() string {
	if m != nil {
		return m.DeploymentTicket
	}
	return ""
}

func (m *ChromeBrowserMachine) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// ChromeOSMachine refers duts and servers in Chrome OS lab
type ChromeOSMachine struct {
	// All infos come from the HaRT system.
	// used by referencing device config.
	ReferenceBoard string `protobuf:"bytes,1,opt,name=reference_board,json=referenceBoard,proto3" json:"reference_board,omitempty"`
	// used by ChromeOS build system.
	BuildTarget string `protobuf:"bytes,2,opt,name=build_target,json=buildTarget,proto3" json:"build_target,omitempty"`
	Model       string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// Chromebook, labstation, servo, …
	DeviceType ChromeOSDeviceType `protobuf:"varint,4,opt,name=device_type,json=deviceType,proto3,enum=unifiedfleet.api.v1.proto.ChromeOSDeviceType" json:"device_type,omitempty"`
	// Used internally, Different boards/models could share the same name.
	GoogleCodeName string `protobuf:"bytes,5,opt,name=google_code_name,json=googleCodeName,proto3" json:"google_code_name,omitempty"`
	// HaRT doesn't guarantee its existence.
	MacAddress           string   `protobuf:"bytes,6,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Sku                  string   `protobuf:"bytes,7,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChromeOSMachine) Reset()         { *m = ChromeOSMachine{} }
func (m *ChromeOSMachine) String() string { return proto.CompactTextString(m) }
func (*ChromeOSMachine) ProtoMessage()    {}
func (*ChromeOSMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcb58b98328ec12c, []int{2}
}

func (m *ChromeOSMachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChromeOSMachine.Unmarshal(m, b)
}
func (m *ChromeOSMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChromeOSMachine.Marshal(b, m, deterministic)
}
func (m *ChromeOSMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChromeOSMachine.Merge(m, src)
}
func (m *ChromeOSMachine) XXX_Size() int {
	return xxx_messageInfo_ChromeOSMachine.Size(m)
}
func (m *ChromeOSMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_ChromeOSMachine.DiscardUnknown(m)
}

var xxx_messageInfo_ChromeOSMachine proto.InternalMessageInfo

func (m *ChromeOSMachine) GetReferenceBoard() string {
	if m != nil {
		return m.ReferenceBoard
	}
	return ""
}

func (m *ChromeOSMachine) GetBuildTarget() string {
	if m != nil {
		return m.BuildTarget
	}
	return ""
}

func (m *ChromeOSMachine) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *ChromeOSMachine) GetDeviceType() ChromeOSDeviceType {
	if m != nil {
		return m.DeviceType
	}
	return ChromeOSDeviceType_CHROME_OS_DEVICE_TYPE_UNSPECIFIED
}

func (m *ChromeOSMachine) GetGoogleCodeName() string {
	if m != nil {
		return m.GoogleCodeName
	}
	return ""
}

func (m *ChromeOSMachine) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *ChromeOSMachine) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func init() {
	proto.RegisterEnum("unifiedfleet.api.v1.proto.ChromeOSDeviceType", ChromeOSDeviceType_name, ChromeOSDeviceType_value)
	proto.RegisterType((*Machine)(nil), "unifiedfleet.api.v1.proto.Machine")
	proto.RegisterType((*ChromeBrowserMachine)(nil), "unifiedfleet.api.v1.proto.ChromeBrowserMachine")
	proto.RegisterType((*ChromeOSMachine)(nil), "unifiedfleet.api.v1.proto.ChromeOSMachine")
}

func init() {
	proto.RegisterFile("infra/appengine/unified-fleet/api/v1/proto/machine.proto", fileDescriptor_bcb58b98328ec12c)
}

var fileDescriptor_bcb58b98328ec12c = []byte{
	// 875 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xd1, 0x6e, 0xdb, 0x36,
	0x14, 0x4d, 0xe2, 0x24, 0x4d, 0xe8, 0xb4, 0x51, 0x89, 0xac, 0xf0, 0xf2, 0xb0, 0xa4, 0x29, 0x86,
	0x66, 0x1d, 0x22, 0xb5, 0xee, 0xcb, 0xb6, 0x0e, 0xeb, 0x6c, 0xc7, 0x43, 0x8c, 0x26, 0x76, 0x20,
	0x7b, 0x01, 0x36, 0x0c, 0x10, 0x68, 0xea, 0xca, 0x26, 0x2c, 0x89, 0x04, 0x45, 0x39, 0x30, 0x8a,
	0xfd, 0xcb, 0x3e, 0x63, 0x9f, 0xb3, 0xe7, 0x7e, 0xc5, 0x20, 0x92, 0x72, 0xbc, 0xad, 0x8b, 0xeb,
	0x37, 0xde, 0xc3, 0x7b, 0xce, 0x15, 0xef, 0x3d, 0xd7, 0x46, 0xdf, 0xb0, 0x34, 0x92, 0xc4, 0x23,
	0x42, 0x40, 0x3a, 0x62, 0x29, 0x78, 0x79, 0xca, 0x22, 0x06, 0xe1, 0x59, 0x14, 0x03, 0x28, 0x8f,
	0x08, 0xe6, 0x4d, 0x5f, 0x79, 0x42, 0x72, 0xc5, 0xbd, 0x84, 0xd0, 0x31, 0x4b, 0xc1, 0xd5, 0x11,
	0xfe, 0xdc, 0x66, 0xea, 0x44, 0x97, 0x08, 0xe6, 0x4e, 0x5f, 0x99, 0xab, 0xc3, 0xa3, 0x11, 0xe7,
	0xa3, 0x18, 0x0c, 0x6d, 0x98, 0x47, 0x9e, 0x62, 0x09, 0x64, 0x8a, 0x24, 0xc2, 0x26, 0x7c, 0x3b,
	0xe2, 0x2e, 0x1d, 0x4b, 0x9e, 0xb0, 0x3c, 0x71, 0xb9, 0x1c, 0x79, 0x71, 0x4e, 0x99, 0x37, 0x92,
	0x82, 0xda, 0x52, 0x56, 0xa0, 0x28, 0x2f, 0x21, 0xe3, 0xb9, 0xa4, 0xb6, 0xec, 0xe1, 0xdb, 0x15,
	0xa8, 0x11, 0x83, 0x38, 0x0c, 0x86, 0x30, 0x26, 0x53, 0xc6, 0xa5, 0x15, 0xf8, 0x71, 0x85, 0x17,
	0xeb, 0x42, 0x10, 0x88, 0x98, 0xa8, 0x88, 0xcb, 0xa4, 0xfc, 0xfa, 0x15, 0x14, 0x62, 0x4e, 0x89,
	0x62, 0x3c, 0xb5, 0xd4, 0xef, 0x57, 0xa0, 0x0a, 0x90, 0x4c, 0x8c, 0x41, 0x92, 0x38, 0xb3, 0xec,
	0x55, 0x86, 0x95, 0x82, 0xba, 0xe5, 0x72, 0x62, 0x98, 0x27, 0x1f, 0x2a, 0xe8, 0xc1, 0x95, 0x19,
	0x1f, 0xc6, 0x68, 0x33, 0x25, 0x09, 0xd4, 0xd6, 0x8f, 0xd7, 0x4f, 0x77, 0x7d, 0x7d, 0xc6, 0xcf,
	0xd0, 0xc3, 0x0c, 0x24, 0x23, 0x71, 0x90, 0xe6, 0xc9, 0x10, 0x64, 0x6d, 0x43, 0x5f, 0xee, 0x19,
	0xb0, 0xab, 0x31, 0xfc, 0x16, 0xed, 0x94, 0xcf, 0xa9, 0x55, 0x8e, 0xd7, 0x4f, 0xab, 0xf5, 0x67,
	0xee, 0xff, 0x9a, 0xc0, 0xbd, 0xb4, 0xa9, 0xfe, 0x9c, 0x84, 0x47, 0xe8, 0x89, 0xed, 0xe8, 0x50,
	0xf2, 0xdb, 0x0c, 0x64, 0x60, 0x2d, 0x55, 0xdb, 0xd4, 0x72, 0xde, 0x3d, 0x72, 0x2d, 0x4d, 0x6c,
	0x1a, 0x9e, 0x7d, 0xca, 0xc5, 0x9a, 0x7f, 0x40, 0x3f, 0x82, 0xe3, 0xdf, 0x90, 0x63, 0x70, 0x9e,
	0xcd, 0x4b, 0x6c, 0xe9, 0x12, 0x2f, 0x96, 0x96, 0xe8, 0xf5, 0xad, 0x4a, 0xb3, 0xf2, 0x57, 0xa3,
	0x72, 0xb1, 0xe6, 0xef, 0x97, 0x52, 0xa5, 0xfa, 0x1b, 0x54, 0xcd, 0x45, 0x48, 0x14, 0x04, 0x85,
	0xaf, 0x6b, 0xdb, 0x5a, 0xf8, 0xd0, 0x35, 0xc6, 0x73, 0x4b, 0xd3, 0xbb, 0x83, 0xd2, 0xf4, 0x3e,
	0x32, 0xe9, 0x05, 0x80, 0x0f, 0xd0, 0x96, 0x04, 0x12, 0x27, 0xb5, 0x07, 0xba, 0xc3, 0x26, 0xf8,
	0xae, 0xf1, 0xa1, 0xf1, 0x03, 0x3a, 0xfd, 0xc7, 0x38, 0xcf, 0xb2, 0x59, 0xa6, 0x20, 0x71, 0x89,
	0x10, 0x99, 0xe0, 0xca, 0xa5, 0x3c, 0xf1, 0xe6, 0x23, 0xb4, 0x8f, 0xca, 0xbc, 0xf7, 0xf6, 0xf4,
	0x7b, 0x73, 0x07, 0x6d, 0x87, 0x30, 0x65, 0x14, 0x4e, 0xfe, 0xdc, 0x44, 0x07, 0x1f, 0x6b, 0x17,
	0x7e, 0x8a, 0xf6, 0x42, 0x96, 0x89, 0x98, 0xcc, 0x82, 0x05, 0x07, 0x54, 0x2d, 0xd6, 0x2d, 0x8c,
	0xd0, 0x46, 0x3b, 0xa5, 0xdb, 0xb5, 0x07, 0xaa, 0xf5, 0xaf, 0x96, 0x76, 0xec, 0xda, 0x12, 0xfc,
	0x39, 0x15, 0xbf, 0x44, 0x95, 0x94, 0x51, 0xeb, 0x92, 0x2f, 0xee, 0x51, 0xe8, 0x32, 0xea, 0x17,
	0xa9, 0xf8, 0x12, 0x3d, 0x9c, 0x4c, 0x93, 0x80, 0xa5, 0x0a, 0x64, 0x44, 0x68, 0x69, 0x89, 0xe7,
	0xf7, 0x70, 0xdf, 0xdd, 0x5c, 0x75, 0xca, 0x74, 0x7f, 0x6f, 0x32, 0x4d, 0xe6, 0x51, 0xa1, 0x26,
	0xc5, 0xa2, 0xda, 0xd6, 0x52, 0x35, 0xff, 0x7a, 0x51, 0x4d, 0x8a, 0x05, 0xb5, 0x10, 0xd5, 0xec,
	0x3a, 0x05, 0xa6, 0xc5, 0x0b, 0xc2, 0xdb, 0x4b, 0x6d, 0xd5, 0xbf, 0x65, 0x8a, 0x8e, 0xef, 0xb4,
	0x9f, 0x58, 0xad, 0x73, 0x2d, 0x75, 0x57, 0xe5, 0x35, 0xda, 0x0c, 0x25, 0xa1, 0xda, 0x18, 0xd5,
	0xfa, 0xd1, 0x3d, 0x8a, 0xe7, 0x92, 0x50, 0x5f, 0x27, 0xe3, 0xaf, 0xd1, 0xe3, 0x10, 0x44, 0xcc,
	0x67, 0x09, 0xa4, 0x2a, 0x50, 0x8c, 0x4e, 0x40, 0xd5, 0x76, 0xf4, 0x5c, 0x9d, 0xbb, 0x8b, 0x81,
	0xc6, 0xf1, 0x31, 0xaa, 0x86, 0x90, 0x51, 0xc9, 0x84, 0xde, 0xe1, 0x5d, 0x3b, 0xfe, 0x3b, 0xe8,
	0xe4, 0x8f, 0x0d, 0xb4, 0xff, 0xaf, 0x35, 0xc0, 0xcf, 0xd1, 0xbe, 0x84, 0x08, 0x24, 0xa4, 0x14,
	0x82, 0x21, 0x27, 0x32, 0xb4, 0xc6, 0x79, 0x34, 0x87, 0x9b, 0x05, 0x5a, 0xd8, 0x6b, 0x98, 0xb3,
	0x38, 0x0c, 0x14, 0x91, 0x23, 0x50, 0xf6, 0x37, 0xa4, 0xaa, 0xb1, 0x81, 0x86, 0x0a, 0xf7, 0x27,
	0x3c, 0x84, 0x58, 0x3b, 0x63, 0xd7, 0x37, 0x01, 0xee, 0x16, 0xdf, 0xa5, 0xfb, 0xaa, 0x66, 0xc2,
	0x4c, 0xfe, 0x51, 0xfd, 0xec, 0x13, 0x36, 0xd5, 0xb4, 0x70, 0x30, 0x13, 0xe0, 0xa3, 0x70, 0x7e,
	0xc6, 0xa7, 0xc8, 0x31, 0xcb, 0x18, 0x50, 0x1e, 0x82, 0xf1, 0xfa, 0x96, 0xf9, 0x64, 0x83, 0xb7,
	0x78, 0x08, 0xda, 0xee, 0x47, 0xa8, 0x9a, 0x10, 0x1a, 0x90, 0x30, 0x94, 0x90, 0x65, 0x7a, 0x98,
	0xbb, 0x3e, 0x4a, 0x08, 0x6d, 0x18, 0x04, 0x3b, 0xa8, 0x92, 0x4d, 0x72, 0xbb, 0xac, 0xc5, 0xf1,
	0xc5, 0x7b, 0x84, 0xff, 0x5b, 0x1e, 0x7f, 0x89, 0x9e, 0xb6, 0x2e, 0xfc, 0xde, 0x55, 0x3b, 0xe8,
	0xf5, 0x83, 0xf3, 0xf6, 0x4d, 0xa7, 0xd5, 0x0e, 0x06, 0xbf, 0x5c, 0xb7, 0x83, 0x9f, 0xbb, 0xfd,
	0xeb, 0x76, 0xab, 0xf3, 0x53, 0xa7, 0x7d, 0xee, 0xac, 0xe1, 0xcf, 0xd0, 0x63, 0x7b, 0x69, 0xb2,
	0x9b, 0xbd, 0xde, 0x3b, 0x67, 0x7d, 0x01, 0xbe, 0x6c, 0x34, 0xfb, 0x83, 0xc6, 0xa0, 0xd3, 0xeb,
	0x3a, 0x1b, 0xd8, 0x41, 0x7b, 0x16, 0xee, 0xb7, 0xfd, 0x9b, 0x9e, 0x53, 0x69, 0xd6, 0x7f, 0x7d,
	0xf9, 0xe9, 0xff, 0x01, 0x6f, 0xf2, 0x28, 0x13, 0xc3, 0xe1, 0xb6, 0x0e, 0x5e, 0xff, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x9d, 0x3b, 0x35, 0xee, 0xeb, 0x07, 0x00, 0x00,
}
