# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromeperf/engine/graph.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromeperf.engine import task_pb2 as chromeperf_dot_engine_dot_task__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromeperf/engine/graph.proto',
  package='chromeperf.engine',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x63hromeperf/engine/graph.proto\x12\x11\x63hromeperf.engine\x1a\x1c\x63hromeperf/engine/task.proto\"\xf2\x01\n\x05Graph\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x32\n\x05tasks\x18\x02 \x03(\x0b\x32#.chromeperf.engine.Graph.TasksEntry\x12\x39\n\x0c\x64\x65pendencies\x18\x03 \x03(\x0b\x32#.chromeperf.engine.Graph.Dependency\x1a\x45\n\nTasksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.chromeperf.engine.Task:\x02\x38\x01\x1a\'\n\nDependency\x12\r\n\x05\x66rom_\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\tb\x06proto3'
  ,
  dependencies=[chromeperf_dot_engine_dot_task__pb2.DESCRIPTOR,])




_GRAPH_TASKSENTRY = _descriptor.Descriptor(
  name='TasksEntry',
  full_name='chromeperf.engine.Graph.TasksEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='chromeperf.engine.Graph.TasksEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='chromeperf.engine.Graph.TasksEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=284,
)

_GRAPH_DEPENDENCY = _descriptor.Descriptor(
  name='Dependency',
  full_name='chromeperf.engine.Graph.Dependency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_', full_name='chromeperf.engine.Graph.Dependency.from_', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to', full_name='chromeperf.engine.Graph.Dependency.to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=325,
)

_GRAPH = _descriptor.Descriptor(
  name='Graph',
  full_name='chromeperf.engine.Graph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chromeperf.engine.Graph.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tasks', full_name='chromeperf.engine.Graph.tasks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dependencies', full_name='chromeperf.engine.Graph.dependencies', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GRAPH_TASKSENTRY, _GRAPH_DEPENDENCY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=325,
)

_GRAPH_TASKSENTRY.fields_by_name['value'].message_type = chromeperf_dot_engine_dot_task__pb2._TASK
_GRAPH_TASKSENTRY.containing_type = _GRAPH
_GRAPH_DEPENDENCY.containing_type = _GRAPH
_GRAPH.fields_by_name['tasks'].message_type = _GRAPH_TASKSENTRY
_GRAPH.fields_by_name['dependencies'].message_type = _GRAPH_DEPENDENCY
DESCRIPTOR.message_types_by_name['Graph'] = _GRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Graph = _reflection.GeneratedProtocolMessageType('Graph', (_message.Message,), {

  'TasksEntry' : _reflection.GeneratedProtocolMessageType('TasksEntry', (_message.Message,), {
    'DESCRIPTOR' : _GRAPH_TASKSENTRY,
    '__module__' : 'chromeperf.engine.graph_pb2'
    # @@protoc_insertion_point(class_scope:chromeperf.engine.Graph.TasksEntry)
    })
  ,

  'Dependency' : _reflection.GeneratedProtocolMessageType('Dependency', (_message.Message,), {
    'DESCRIPTOR' : _GRAPH_DEPENDENCY,
    '__module__' : 'chromeperf.engine.graph_pb2'
    # @@protoc_insertion_point(class_scope:chromeperf.engine.Graph.Dependency)
    })
  ,
  'DESCRIPTOR' : _GRAPH,
  '__module__' : 'chromeperf.engine.graph_pb2'
  # @@protoc_insertion_point(class_scope:chromeperf.engine.Graph)
  })
_sym_db.RegisterMessage(Graph)
_sym_db.RegisterMessage(Graph.TasksEntry)
_sym_db.RegisterMessage(Graph.Dependency)


_GRAPH_TASKSENTRY._options = None
# @@protoc_insertion_point(module_scope)
