// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/unifiedfleet/api/v1/proto/bigquery/bq.proto

package apibq

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "infra/unifiedfleet/api/v1/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChromePlatformRow struct {
	Platform             *proto1.ChromePlatform `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ChromePlatformRow) Reset()         { *m = ChromePlatformRow{} }
func (m *ChromePlatformRow) String() string { return proto.CompactTextString(m) }
func (*ChromePlatformRow) ProtoMessage()    {}
func (*ChromePlatformRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_22874a6069af15db, []int{0}
}

func (m *ChromePlatformRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChromePlatformRow.Unmarshal(m, b)
}
func (m *ChromePlatformRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChromePlatformRow.Marshal(b, m, deterministic)
}
func (m *ChromePlatformRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChromePlatformRow.Merge(m, src)
}
func (m *ChromePlatformRow) XXX_Size() int {
	return xxx_messageInfo_ChromePlatformRow.Size(m)
}
func (m *ChromePlatformRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ChromePlatformRow.DiscardUnknown(m)
}

var xxx_messageInfo_ChromePlatformRow proto.InternalMessageInfo

func (m *ChromePlatformRow) GetPlatform() *proto1.ChromePlatform {
	if m != nil {
		return m.Platform
	}
	return nil
}

func init() {
	proto.RegisterType((*ChromePlatformRow)(nil), "unifiedfleet.api.v1.proto.bigquery.ChromePlatformRow")
}

func init() {
	proto.RegisterFile("infra/unifiedfleet/api/v1/proto/bigquery/bq.proto", fileDescriptor_22874a6069af15db)
}

var fileDescriptor_22874a6069af15db = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xcc, 0xcc, 0x4b, 0x2b,
	0x4a, 0xd4, 0x2f, 0xcd, 0xcb, 0x4c, 0xcb, 0x4c, 0x4d, 0x49, 0xcb, 0x49, 0x4d, 0x2d, 0xd1, 0x4f,
	0x2c, 0xc8, 0xd4, 0x2f, 0x33, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xca, 0x4c, 0x2f,
	0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x4f, 0x2a, 0xd4, 0x03, 0x8b, 0x08, 0x29, 0x21, 0x2b, 0xd6, 0x4b,
	0x2c, 0xc8, 0xd4, 0x2b, 0x33, 0x84, 0x48, 0xe9, 0xc1, 0x14, 0x4b, 0x99, 0x12, 0x32, 0x36, 0x39,
	0xa3, 0x28, 0x3f, 0x37, 0x35, 0xbe, 0x20, 0x27, 0xb1, 0x24, 0x2d, 0xbf, 0x28, 0x17, 0xa2, 0x5f,
	0x29, 0x8a, 0x4b, 0xd0, 0x19, 0x2c, 0x11, 0x00, 0x15, 0x0f, 0xca, 0x2f, 0x17, 0x72, 0xe5, 0xe2,
	0x80, 0x29, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0xd2, 0xd4, 0xc3, 0xed, 0x04, 0x34, 0xfd,
	0x70, 0xad, 0x4e, 0x06, 0x51, 0x7a, 0xc4, 0xfa, 0xd5, 0x3a, 0xb1, 0x20, 0x33, 0xa9, 0x30, 0x89,
	0x0d, 0x2c, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x41, 0x99, 0x93, 0x79, 0x24, 0x01, 0x00,
	0x00,
}
