# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/api_proto/project_objects.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google_proto.google.api import field_behavior_pb2 as google__proto_dot_google_dot_api_dot_field__behavior__pb2
from google_proto.google.api import resource_pb2 as google__proto_dot_google_dot_api_dot_resource__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/v1/api_proto/project_objects.proto',
  package='monorail.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&api/v1/api_proto/project_objects.proto\x12\x0bmonorail.v1\x1a,google_proto/google/api/field_behavior.proto\x1a&google_proto/google/api/resource.proto\"G\n\x07Project\x12\x0c\n\x04name\x18\x01 \x01(\t:.\xea\x41+\n\x15\x61pi.crbug.com/Project\x12\x12projects/{project}\"b\n\tStatusDef\x12\x0c\n\x04name\x18\x01 \x01(\t:G\xea\x41\x44\n\x17\x61pi.crbug.com/StatusDef\x12)projects/{project}/statusDefs/{statusDef}\"^\n\x08LabelDef\x12\x0c\n\x04name\x18\x01 \x01(\t:D\xea\x41\x41\n\x16\x61pi.crbug.com/LabelDef\x12\'projects/{project}/labelDefs/{labelDef}\"^\n\x08\x46ieldDef\x12\x0c\n\x04name\x18\x01 \x01(\t:D\xea\x41\x41\n\x16\x61pi.crbug.com/FieldDef\x12\'projects/{project}/fieldDefs/{fieldDef}\"n\n\x0c\x43omponentDef\x12\x0c\n\x04name\x18\x01 \x01(\t:P\xea\x41M\n\x1a\x61pi.crbug.com/ComponentDef\x12/projects/{project}/componentDefs/{componentDef}\"j\n\x0b\x41pprovalDef\x12\x0c\n\x04name\x18\x01 \x01(\t:M\xea\x41J\n\x19\x61pi.crbug.com/ApprovalDef\x12-projects/{project}/approvalDefs/{approvalDef}b\x06proto3')
  ,
  dependencies=[google__proto_dot_google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,google__proto_dot_google_dot_api_dot_resource__pb2.DESCRIPTOR,])




_PROJECT = _descriptor.Descriptor(
  name='Project',
  full_name='monorail.v1.Project',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='monorail.v1.Project.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\352A+\n\025api.crbug.com/Project\022\022projects/{project}'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=212,
)


_STATUSDEF = _descriptor.Descriptor(
  name='StatusDef',
  full_name='monorail.v1.StatusDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='monorail.v1.StatusDef.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\352AD\n\027api.crbug.com/StatusDef\022)projects/{project}/statusDefs/{statusDef}'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=312,
)


_LABELDEF = _descriptor.Descriptor(
  name='LabelDef',
  full_name='monorail.v1.LabelDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='monorail.v1.LabelDef.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\352AA\n\026api.crbug.com/LabelDef\022\'projects/{project}/labelDefs/{labelDef}'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=408,
)


_FIELDDEF = _descriptor.Descriptor(
  name='FieldDef',
  full_name='monorail.v1.FieldDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='monorail.v1.FieldDef.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\352AA\n\026api.crbug.com/FieldDef\022\'projects/{project}/fieldDefs/{fieldDef}'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=504,
)


_COMPONENTDEF = _descriptor.Descriptor(
  name='ComponentDef',
  full_name='monorail.v1.ComponentDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='monorail.v1.ComponentDef.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\352AM\n\032api.crbug.com/ComponentDef\022/projects/{project}/componentDefs/{componentDef}'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=616,
)


_APPROVALDEF = _descriptor.Descriptor(
  name='ApprovalDef',
  full_name='monorail.v1.ApprovalDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='monorail.v1.ApprovalDef.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\352AJ\n\031api.crbug.com/ApprovalDef\022-projects/{project}/approvalDefs/{approvalDef}'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=724,
)

DESCRIPTOR.message_types_by_name['Project'] = _PROJECT
DESCRIPTOR.message_types_by_name['StatusDef'] = _STATUSDEF
DESCRIPTOR.message_types_by_name['LabelDef'] = _LABELDEF
DESCRIPTOR.message_types_by_name['FieldDef'] = _FIELDDEF
DESCRIPTOR.message_types_by_name['ComponentDef'] = _COMPONENTDEF
DESCRIPTOR.message_types_by_name['ApprovalDef'] = _APPROVALDEF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Project = _reflection.GeneratedProtocolMessageType('Project', (_message.Message,), dict(
  DESCRIPTOR = _PROJECT,
  __module__ = 'api.v1.api_proto.project_objects_pb2'
  # @@protoc_insertion_point(class_scope:monorail.v1.Project)
  ))
_sym_db.RegisterMessage(Project)

StatusDef = _reflection.GeneratedProtocolMessageType('StatusDef', (_message.Message,), dict(
  DESCRIPTOR = _STATUSDEF,
  __module__ = 'api.v1.api_proto.project_objects_pb2'
  # @@protoc_insertion_point(class_scope:monorail.v1.StatusDef)
  ))
_sym_db.RegisterMessage(StatusDef)

LabelDef = _reflection.GeneratedProtocolMessageType('LabelDef', (_message.Message,), dict(
  DESCRIPTOR = _LABELDEF,
  __module__ = 'api.v1.api_proto.project_objects_pb2'
  # @@protoc_insertion_point(class_scope:monorail.v1.LabelDef)
  ))
_sym_db.RegisterMessage(LabelDef)

FieldDef = _reflection.GeneratedProtocolMessageType('FieldDef', (_message.Message,), dict(
  DESCRIPTOR = _FIELDDEF,
  __module__ = 'api.v1.api_proto.project_objects_pb2'
  # @@protoc_insertion_point(class_scope:monorail.v1.FieldDef)
  ))
_sym_db.RegisterMessage(FieldDef)

ComponentDef = _reflection.GeneratedProtocolMessageType('ComponentDef', (_message.Message,), dict(
  DESCRIPTOR = _COMPONENTDEF,
  __module__ = 'api.v1.api_proto.project_objects_pb2'
  # @@protoc_insertion_point(class_scope:monorail.v1.ComponentDef)
  ))
_sym_db.RegisterMessage(ComponentDef)

ApprovalDef = _reflection.GeneratedProtocolMessageType('ApprovalDef', (_message.Message,), dict(
  DESCRIPTOR = _APPROVALDEF,
  __module__ = 'api.v1.api_proto.project_objects_pb2'
  # @@protoc_insertion_point(class_scope:monorail.v1.ApprovalDef)
  ))
_sym_db.RegisterMessage(ApprovalDef)


_PROJECT._options = None
_STATUSDEF._options = None
_LABELDEF._options = None
_FIELDDEF._options = None
_COMPONENTDEF._options = None
_APPROVALDEF._options = None
# @@protoc_insertion_point(module_scope)
