runtime: go116

handlers:
- url: /prpc/.*
  secure: always
  script: auto

- url: /(.*\.(png|css|js|txt))$
  static_files: static/\1
  upload: static/(.*)

- url: /(.*)
  static_files: static/index.html
  upload: static/index.html
