# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: go.chromium.org/luci/tokenserver/api/machine_token.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='go.chromium.org/luci/tokenserver/api/machine_token.proto',
  package='tokenserver',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n8go.chromium.org/luci/tokenserver/api/machine_token.proto\x12\x0btokenserver\"\x80\x01\n\x10MachineTokenBody\x12\x14\n\x0cmachine_fqdn\x18\x01 \x01(\t\x12\x11\n\tissued_by\x18\x02 \x01(\t\x12\x11\n\tissued_at\x18\x03 \x01(\x04\x12\x10\n\x08lifetime\x18\x04 \x01(\x04\x12\r\n\x05\x63\x61_id\x18\x05 \x01(\x03\x12\x0f\n\x07\x63\x65rt_sn\x18\x06 \x01(\x04\"N\n\x14MachineTokenEnvelope\x12\x12\n\ntoken_body\x18\x01 \x01(\x0c\x12\x0e\n\x06key_id\x18\x02 \x01(\t\x12\x12\n\nrsa_sha256\x18\x03 \x01(\x0c*<\n\x10MachineTokenType\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\x16\n\x12LUCI_MACHINE_TOKEN\x10\x02\x62\x06proto3')
)

_MACHINETOKENTYPE = _descriptor.EnumDescriptor(
  name='MachineTokenType',
  full_name='tokenserver.MachineTokenType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LUCI_MACHINE_TOKEN', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=284,
  serialized_end=344,
)
_sym_db.RegisterEnumDescriptor(_MACHINETOKENTYPE)

MachineTokenType = enum_type_wrapper.EnumTypeWrapper(_MACHINETOKENTYPE)
UNKNOWN_TYPE = 0
LUCI_MACHINE_TOKEN = 2



_MACHINETOKENBODY = _descriptor.Descriptor(
  name='MachineTokenBody',
  full_name='tokenserver.MachineTokenBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine_fqdn', full_name='tokenserver.MachineTokenBody.machine_fqdn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='issued_by', full_name='tokenserver.MachineTokenBody.issued_by', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='issued_at', full_name='tokenserver.MachineTokenBody.issued_at', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lifetime', full_name='tokenserver.MachineTokenBody.lifetime', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ca_id', full_name='tokenserver.MachineTokenBody.ca_id', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cert_sn', full_name='tokenserver.MachineTokenBody.cert_sn', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=202,
)


_MACHINETOKENENVELOPE = _descriptor.Descriptor(
  name='MachineTokenEnvelope',
  full_name='tokenserver.MachineTokenEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_body', full_name='tokenserver.MachineTokenEnvelope.token_body', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_id', full_name='tokenserver.MachineTokenEnvelope.key_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rsa_sha256', full_name='tokenserver.MachineTokenEnvelope.rsa_sha256', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=282,
)

DESCRIPTOR.message_types_by_name['MachineTokenBody'] = _MACHINETOKENBODY
DESCRIPTOR.message_types_by_name['MachineTokenEnvelope'] = _MACHINETOKENENVELOPE
DESCRIPTOR.enum_types_by_name['MachineTokenType'] = _MACHINETOKENTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MachineTokenBody = _reflection.GeneratedProtocolMessageType('MachineTokenBody', (_message.Message,), dict(
  DESCRIPTOR = _MACHINETOKENBODY,
  __module__ = 'go.chromium.org.luci.tokenserver.api.machine_token_pb2'
  # @@protoc_insertion_point(class_scope:tokenserver.MachineTokenBody)
  ))
_sym_db.RegisterMessage(MachineTokenBody)

MachineTokenEnvelope = _reflection.GeneratedProtocolMessageType('MachineTokenEnvelope', (_message.Message,), dict(
  DESCRIPTOR = _MACHINETOKENENVELOPE,
  __module__ = 'go.chromium.org.luci.tokenserver.api.machine_token_pb2'
  # @@protoc_insertion_point(class_scope:tokenserver.MachineTokenEnvelope)
  ))
_sym_db.RegisterMessage(MachineTokenEnvelope)


# @@protoc_insertion_point(module_scope)
